services:
  
  vpnclient:
    tty: true
    build:
      context: ../
      dockerfile: client/Dockerfile
    container_name: client1
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    networks:
      external_network:
        ipv4_address: 10.5.0.7

  vpnclient2:
    tty: true
    image: client-vpnclient
    # build:
    #   context: ../
    #   dockerfile: client/Dockerfile
    container_name: client2
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    networks:
      external_network:
        ipv4_address: 10.5.0.8

networks:
  external_network:
    driver: bridge
    ipam:
     config:
      - subnet: 10.5.0.0/24
        gateway: 10.5.0.15