services:
  
  vpnclient:
    tty: true
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - ALL
    build:
      context: ../
      dockerfile: client/Dockerfile
    container_name: client1
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    networks:
      external_network:
        ipv4_address: 10.5.42.7

  vpnclient2:
    tty: true
    devices:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - ALL
    image: dogevpn-vpnclient
    container_name: client2
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
    networks:
      external_network:
        ipv4_address: 10.5.42.8
    depends_on:
      - vpnclient
