services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: vpndb
    networks:
      internal_network:
        ipv4_address: 192.168.0.5
    ports:
    - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  vpnserver:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    cap_add:
      - ALL
    sysctls:
      - net.ipv4.ip_forward=1
    container_name: server
    environment:
      - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    networks:
      external_network:
        ipv4_address: 10.5.0.15
      internal_network:
        ipv4_address: 192.168.0.15

    command: ./build/vpnserver

networks:
  external_network:
    driver: bridge
    ipam:
     config:
      - subnet: 10.5.0.0/24
        gateway: 10.5.0.15

  internal_network:
    driver: bridge
    ipam:
     config:
      - subnet: 192.168.0.0/24
        gateway: 192.168.0.15