all: 
# g++ -o vpnserver vpnserver.c
	g++ -o mongoclient mongo.cpp \
    -I/usr/local/include/libbson-1.0 -I/usr/local/include/libmongoc-1.0 \
    -lmongoc-1.0 -lbson-1.0



clean: 
#	rm vpnserver
	rm mongoclient
